name: Second CI practice

# When this workflow should run
on:
  push:
    branches:
      - main        # run on pushes to main branch
  pull_request:    # also run on pull requests

jobs:
  run-tests:
    runs-on: ubuntu-latest   # the machine GitHub will provide

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'        # Java version used in your project
          distribution: 'temurin'   # standard JDK

      - name: run test
        run: mvn test


